name: 🧪 Claude-Ally Test Suite v2

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'claude-ally.sh'
      - 'setup.sh'
      - 'lib/**'
      - 'contribute-stack.sh'
      - 'stacks/**'
      - 'tests/**'
      - '.github/workflows/test-suite-v2.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'claude-ally.sh'
      - 'setup.sh'
      - 'lib/**'
      - 'contribute-stack.sh'
      - 'stacks/**'
      - 'tests/**'
      - '.github/workflows/test-suite-v2.yml'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - unit
          - integration

jobs:
  # System validation
  validate:
    name: 🔍 System Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate project structure
        run: |
          echo "🔍 Validating claude-ally project structure (v2.1)..."

          # Check core files (updated for reorganized structure)
          required_files=(
            "claude-ally.sh"
            "setup.sh"
            "lib/stack-detector.sh"
            "lib/progress-indicator.sh"
            "lib/error-handler.sh"
            "contribute-stack.sh"
            "README.md"
          )

          for file in "${required_files[@]}"; do
            if [[ -f "$file" ]]; then
              echo "✅ $file found"
            else
              echo "❌ $file missing"
              exit 1
            fi
          done

          # Check directory structure (updated for reorganized structure)
          required_dirs=("tests" "stacks" "lib")
          for dir in "${required_dirs[@]}"; do
            if [[ -d "$dir" ]]; then
              echo "✅ $dir/ directory found"
            else
              echo "❌ $dir/ directory missing"
              exit 1
            fi
          done

          echo "🎉 Project structure validation completed successfully"

      - name: Check executable permissions
        run: |
          echo "🔧 Checking executable permissions..."

          executable_files=(
            "claude-ally.sh"
            "setup.sh"
            "tests/run_all_tests.sh"
            "tests/unit/test_stack_detector.sh"
            "tests/integration/test_cli_integration.sh"
            "tests/end-to-end/test_complete_workflows.sh"
          )

          for file in "${executable_files[@]}"; do
            if [[ -x "$file" ]]; then
              echo "✅ $file is executable"
            else
              echo "⚠️ $file is not executable, fixing..."
              chmod +x "$file"
            fi
          done

      - name: Run system validation
        run: |
          echo "🧪 Running claude-ally system validation..."
          ./claude-ally.sh validate

  # Unit Tests
  unit-tests:
    name: 🧩 Unit Tests
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          echo "🧩 Running unit tests"
          chmod +x tests/run_all_tests.sh
          chmod +x tests/unit/test_stack_detector.sh
          ./tests/run_all_tests.sh unit

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: /tmp/claude-ally-test-*
          retention-days: 7

  # Cross-Platform Tests (minimal for faster execution)
  cross-platform:
    name: 🌍 Cross-Platform Test
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run basic functionality tests
        run: |
          echo "🌍 Testing claude-ally basic functionality"

          # Basic CLI tests
          chmod +x claude-ally.sh
          ./claude-ally.sh --help
          ./claude-ally.sh version
          ./claude-ally.sh validate

          # Test detection on self (should work on all platforms)
          ./claude-ally.sh detect .

      - name: Run unit tests (cross-platform)
        run: |
          echo "🧩 Running unit tests"
          chmod +x tests/run_all_tests.sh
          chmod +x tests/unit/test_stack_detector.sh
          ./tests/run_all_tests.sh unit

  # Final Results
  results:
    name: 📊 Test Results
    runs-on: ubuntu-latest
    needs: [unit-tests, cross-platform]
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate test report
        run: |
          echo "📊 Generating test report"

          # Create test report
          cat > test-report.md << EOF
          # Claude-Ally Test Report v2

          ## Test Execution Summary

          - **Date**: $(date)
          - **Commit**: ${{ github.sha }}
          - **Branch**: ${{ github.ref_name }}
          - **Trigger**: ${{ github.event_name }}

          ## Test Results

          ### Unit Tests
          Status: ${{ needs.unit-tests.result }}

          ### Cross-Platform Tests
          Status: ${{ needs.cross-platform.result }}

          ## Status Badge

          ![Tests](https://github.com/${{ github.repository }}/actions/workflows/test-suite-v2.yml/badge.svg)

          EOF

          echo "📋 Test report generated"

      - name: Set test status
        id: test-status
        run: |
          # Determine overall test status
          if [[ "${{ needs.unit-tests.result }}" == "success" && \
                "${{ needs.cross-platform.result }}" == "success" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "🎉 All critical tests passed successfully!"
          else
            echo "status=partial" >> $GITHUB_OUTPUT
            echo "⚠️ Some tests had issues"

            # Report specific results
            echo "Test Results Summary:"
            echo "- Unit Tests: ${{ needs.unit-tests.result }}"
            echo "- Cross-Platform: ${{ needs.cross-platform.result }}"
          fi

      - name: Update status badge
        if: github.ref == 'refs/heads/main'
        run: |
          echo "🏷️ Test status: ${{ steps.test-status.outputs.status }}"

          # Badge will be automatically updated by GitHub Actions badge system
          if [[ "${{ steps.test-status.outputs.status }}" == "success" ]]; then
            echo "✅ Badge will show: passing"
          else
            echo "⚠️ Badge will show: partial success"
          fi